# Generated by Django 3.2.7 on 2021-09-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortenApp', '0002_alter_urlshortenmodel_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortenmodel',
            name='short_code',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
